name: Deploy Flutter Web

on:
  push:
    branches:
      - "**"

permissions:
  contents:**ead
  pages: write
  id-token: wr**e

concurrency:
  group: pages
  **ncel-in-progress: true

jobs:
**build:
    runs-on: ubuntu-latest**    steps:
     ** name: Checkout
        uses**actions/checkout@v4

      - name**Setup Flutter
        uses: subos**o/flutter-action@v2
        with:**         channel: stable

      -**ame: Flutter Pub Get
        run:**lutter pub get

      - name: Bui** Flutter Web
        run: flutter**uild web --release --base-href /l**nivelsystem/

      - name: Uploa**Pages Artifact
        uses: acti**s/upload-pages-artifact@v3
      **with:
          path: build/web

**deploy:
    needs: build

    run**on: ubuntu-latest

    environmen**
      name: github-pages

    st**s:
      - name: Deploy to GitHub**ages
        id: deployment
     ** uses: actions/deploy-pages@v4
``**
